"""delete age from users

Revision ID: 35b565596bc1
Revises: de837bdd390e
Create Date: 2026-06-06 14:06:39.989119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35b565596bc1'
down_revision: Union[str, Sequence[str], None] = 'de837bdd390e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
